import { AlertCircle, Clock3, Play, RefreshCw, Trash2 } from "lucide-react";
import type { ExecutionPanelState, ExecutionRuntime, PreviewInfo } from "../../types/execution";
import { Button } from "../ui/Button";
import { Textarea } from "../ui/Textarea";

type Props = { state: ExecutionPanelState; isRunning: boolean; isBrowserProject: boolean; onRun: () => void; onPreviewRefresh: () => void; onRuntimeChange: (runtime: ExecutionRuntime) => void; runtime: ExecutionRuntime; runLabel: string; stdin: string; onStdinChange: (value: string) => void; timeoutMs: number; onTimeoutChange: (value: number) => void; onClear: () => void; preview?: PreviewInfo; previewError?: string };
const consoleText = (value: string) => <pre className="execution-console mt-2 overflow-x-auto whitespace-pre-wrap wrap-break-words rounded-xl bg-(--color-surface-secondary) p-3 font-mono text-xs leading-5 text-text">{value}</pre>;

export function ExecutionOutput({ state, isRunning, isBrowserProject, onRun, onPreviewRefresh, onRuntimeChange, runtime, runLabel, stdin, onStdinChange, timeoutMs, onTimeoutChange, onClear, preview, previewError }: Props) {
  const result = "result" in state ? state.result : undefined;
  const message = state.status === "api-error" ? state.message : result?.stderr || result?.error?.message;
  return <section className="flex min-h-[380px] min-w-0 flex-col bg-elevated xl:min-h-0"><div className="flex shrink-0 items-center justify-between border-b border-border-subtle px-4 py-3"><div><h2 className="text-sm font-semibold text-text">{isBrowserProject ? "Browser preview" : "Execution"}</h2><p className="text-xs text-muted">{isBrowserProject ? "Browser runtime" : `${runtime === "browser" ? "Browser" : "Node.js"} runtime`}</p></div><div className="flex items-center gap-2">{!isBrowserProject && <select className="h-9 rounded-lg border border-border bg-app px-2 text-xs text-text" disabled={isRunning} onChange={(event) => onRuntimeChange(event.target.value as ExecutionRuntime)} value={runtime}><option value="node">Node.js</option><option value="browser">Browser</option></select>}<Button disabled={isRunning} isLoading={isRunning} onClick={onRun} type="button"><Play className="size-4" />{isRunning ? "Working..." : runLabel}</Button></div></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-4">{isBrowserProject ? <><div className="mb-3 flex items-center justify-between"><p className="text-sm font-medium text-text">Preview</p>{preview && <button className="rounded-lg p-2 text-muted hover:bg-hover hover:text-text" onClick={onPreviewRefresh} title="Refresh preview" type="button"><RefreshCw className="size-4" /></button>}</div>{preview ? <iframe className="h-72 w-full rounded-xl border border-border bg-white" sandbox="allow-scripts allow-forms allow-modals" src={preview.url} title="Snippet browser preview" /> : <div className="flex h-72 items-center justify-center rounded-xl border border-dashed border-border bg-app px-4 text-center text-xs text-muted">Create a preview to see your browser project.</div>}{previewError && <div className="mt-3 flex gap-2 rounded-lg border border-danger/30 p-3 text-xs text-danger"><AlertCircle className="size-4 shrink-0" />{previewError}</div>}{preview?.expiresAt && <p className="mt-2 text-xs text-muted">Preview expires {new Date(preview.expiresAt).toLocaleTimeString()}.</p>}</> : <><Textarea className="min-h-24 font-mono text-xs" disabled={isRunning} label="Input (stdin)" onChange={(event) => onStdinChange(event.target.value)} placeholder="Enter program input..." value={stdin} /><label className="mt-4 grid gap-2 text-xs font-medium text-muted">Timeout<select className="h-9 rounded-lg border border-border bg-app px-2 text-sm text-text" disabled={isRunning} onChange={(event) => onTimeoutChange(Number(event.target.value))} value={timeoutMs}><option value={1000}>1 second</option><option value={5000}>5 seconds</option><option value={10000}>10 seconds</option><option value={30000}>30 seconds</option></select></label>{state.status === "running" && <p className="mt-5 flex items-center gap-2 text-sm text-muted"><Clock3 className="size-4 animate-spin" />Running code…</p>}{message && <div className="mt-5"><p className="text-sm font-medium text-danger">Execution error</p>{consoleText(message)}</div>}{result?.stdout && <div className="mt-5"><p className="text-sm font-medium text-text">Output</p>{consoleText(result.stdout)}</div>}{result?.browserConsole?.length && <div className="mt-5"><p className="text-sm font-medium text-text">Browser console</p>{consoleText(result.browserConsole.map((entry) => `[${entry.level.toUpperCase()}] ${entry.message}`).join("\n"))}</div>}{result && <div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-app p-3">Exit code<br /><strong className="text-text">{result.exitCode ?? "-"}</strong></div><div className="rounded-lg bg-app p-3">Duration<br /><strong className="text-text">{result.durationMs}ms</strong></div></div>}</>}<button className="mt-5 flex items-center gap-2 text-xs text-muted hover:text-text" onClick={onClear} type="button"><Trash2 className="size-3.5" />Clear result</button></div></section>;
}
