import { Controller, useForm } from "react-hook-form";
import { useEffect, useMemo, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { FileCode2, FolderTree } from "lucide-react";
import { toast } from "sonner";
import { languageLabels, languages } from "../../features/snippets/languages";
import { useRunExecution } from "../../services/useExecution";
import { usePreview } from "../../services/usePreview";
import { useProjects } from "../../services/useProjects";
import { useSnippets } from "../../services/useSnippets";
import type { Snippet, SnippetInput } from "../../types/snippet";
import type { ExecutionRuntime } from "../../types/execution";
import { ExecutionOutput } from "./ExecutionOutput";
import { Input } from "../ui/Input";
import { Textarea } from "../ui/Textarea";
import { SnippetEditor } from "./SnippetEditor";

const schema = z.object({ title: z.string().trim().min(2, "Title must be at least 2 characters.").max(120), description: z.string().trim().max(500, "Description cannot exceed 500 characters."), language: z.enum(languages, "Choose a language."), code: z.string().trim().min(1, "Code cannot be empty."), projectId: z.string().optional(), filePath: z.string().trim().max(512, "File path cannot exceed 512 characters.").optional() }).superRefine((values, context) => { if (!values.projectId) return; const filePath = values.filePath?.trim(); if (!filePath) context.addIssue({ code: "custom", message: "File path is required for project snippets.", path: ["filePath"] }); else if (filePath.includes("\0") || filePath.startsWith("/") || filePath.includes(":") || filePath.includes("\\") || filePath.split("/").some((part) => !part || part === "." || part === "..")) context.addIssue({ code: "custom", message: "Use a safe path relative to the project root.", path: ["filePath"] }); });
type Values = z.infer<typeof schema>;

export function SnippetForm({ formId, snippet, isSubmitting, onEditorFullscreenChange, onSubmit }: { formId: string; snippet?: Snippet; isSubmitting: boolean; onEditorFullscreenChange: (isFullscreen: boolean) => void; onSubmit: (input: SnippetInput) => void; }) {
  const { data: projects } = useProjects({ limit: 100, sort: "name", order: "asc" });
  const { control, formState: { errors, isDirty }, register, watch, handleSubmit, setValue } = useForm<Values>({ defaultValues: { title: snippet?.title ?? "", description: snippet?.description ?? "", language: snippet?.language ?? "typescript", code: snippet?.code ?? "", projectId: snippet?.projectId ?? "", filePath: snippet?.filePath ?? "" }, resolver: zodResolver(schema) });
  const language = watch("language"), projectId = watch("projectId"), filePath = watch("filePath"), code = watch("code");
  const projectSnippets = useSnippets({ projectId: projectId || "__none__", limit: 100, sort: "title", order: "asc" });
  const nodeExecution = useRunExecution(); const preview = usePreview(); const [stdin, setStdin] = useState(""); const [timeoutMs, setTimeoutMs] = useState(10000); const [runtime, setRuntime] = useState<ExecutionRuntime>("node"); const isBrowserProject = language === "html";
  useEffect(() => { nodeExecution.clear(); preview.clear(); if (language === "html") setRuntime("browser"); }, [language]);
  const files = useMemo(() => { const currentPath = filePath?.trim() || "index.html"; const others = projectId ? (projectSnippets.data?.snippets ?? []).filter((item) => item.id !== snippet?.id).map((item) => ({ path: item.filePath || item.title, content: item.code })) : []; return [...others.filter((item) => item.path !== currentPath), { path: currentPath, content: code }]; }, [code, filePath, projectId, projectSnippets.data?.snippets, snippet?.id]);
  const entryPoint = files.find((file) => file.path === "index.html")?.path ?? (language === "html" ? (filePath?.trim() || "index.html") : "index.js");
  const run = () => { if (!code.trim()) return toast.error("Nothing to run."); if (isBrowserProject) { if (!files.some((file) => file.path === entryPoint && file.path.endsWith(".html"))) return toast.error("Browser previews need an HTML entry point."); preview.create({ language: "html", runtime: "browser", entryPoint, files }); return; } if (language !== "javascript" && language !== "typescript") return toast.error("Only JavaScript and TypeScript can be run with Node.js."); if (projectId) { if (!filePath?.trim()) return toast.error("Project snippets need a file path before they can be run."); if (isDirty) toast.info("Project execution uses saved project files. Save changes to run your edits."); nodeExecution.runProject(projectId, { entryPoint: filePath, stdin, timeoutMs }); } else nodeExecution.runStandalone({ language, runtime, framework: runtime, entryPoint: "index.js", files: [{ path: "index.js", content: code }], stdin, timeoutMs }); };
  return <form className="grid min-h-0 grid-cols-1 overflow-y-auto xl:h-full xl:grid-cols-[minmax(210px,.42fr)_minmax(0,1.2fr)_minmax(320px,.62fr)] xl:overflow-hidden" id={formId} noValidate onSubmit={handleSubmit((values) => onSubmit({ ...values, projectId: values.projectId || undefined, filePath: values.projectId ? values.filePath || undefined : null }))}>
    <aside className="min-h-0 overflow-y-auto border-b border-border-subtle bg-elevated p-4 xl:border-r xl:border-b-0"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-text"><FolderTree className="size-4 text-primary" /> File details</div><div className="space-y-4"><Input autoFocus disabled={isSubmitting} error={errors.title?.message} label="Snippet title" {...register("title")} /><Textarea className="min-h-24 resize-none" disabled={isSubmitting} error={errors.description?.message} label="Description" {...register("description")} /><label className="grid gap-2 text-sm font-medium text-text">Language<select className="h-10 rounded-xl border border-border bg-app px-3 text-sm text-text" disabled={isSubmitting} {...register("language")}>{languages.map((item) => <option key={item} value={item}>{languageLabels[item]}</option>)}</select></label><label className="grid gap-2 text-sm font-medium text-text">Project<select className="h-10 rounded-xl border border-border bg-app px-3 text-sm text-text" disabled={isSubmitting} {...register("projectId")}><option value="">Personal snippet</option>{projects?.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>{projectId && <Input disabled={isSubmitting} error={errors.filePath?.message} helperText="Relative to project root" label="File path" placeholder="index.html" {...register("filePath")} />}</div><div className="mt-6 border-t border-border-subtle pt-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">{projectId ? "Project files" : "File"}</p><button className="flex w-full items-center gap-2 rounded-lg bg-primary/10 px-3 py-2 text-left text-sm text-primary" onClick={() => projectId && setValue("filePath", filePath || "index.html", { shouldDirty: true })} type="button"><FileCode2 className="size-4" />{filePath || (language === "html" ? "index.html" : "snippet")}</button>{projectId && projectSnippets.data?.snippets.filter((item) => item.id !== snippet?.id).map((item) => <div className="mt-1 flex items-center gap-2 px-3 py-2 text-xs text-muted" key={item.id}><FileCode2 className="size-3.5" />{item.filePath || item.title}</div>)}</div></aside>
    <main className="min-h-[420px] min-w-0 border-b border-border-subtle p-4 xl:min-h-0 xl:border-r xl:border-b-0"><Controller control={control} name="code" render={({ field }) => <SnippetEditor className="h-full min-h-[390px]" disabled={isSubmitting} error={errors.code?.message} language={language} onChange={field.onChange} onFullscreenChange={onEditorFullscreenChange} value={field.value} />} /></main>
    <Controller control={control} name="code" render={() => <ExecutionOutput isBrowserProject={isBrowserProject} isRunning={isBrowserProject ? preview.isCreating : nodeExecution.isRunning} onClear={() => { nodeExecution.clear(); preview.clear(); }} onPreviewRefresh={run} onRun={run} onRuntimeChange={setRuntime} preview={preview.preview} previewError={preview.error} runLabel={isBrowserProject ? "Preview" : projectId ? "Run project" : "Run"} runtime={runtime} stdin={stdin} onStdinChange={setStdin} onTimeoutChange={setTimeoutMs} state={nodeExecution.state} timeoutMs={timeoutMs} />} />
  </form>;
}
